development: &default
  adapter: postgresql
  database: solar_cun_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  username: dawid
  password: polcode

test:
  <<: *default
  database: solar_cun_test
